yourName = input("What's your name?: ")
print("that's a pretty silly fuckin stupid name")
goodFood = input("what's ur favorite food?: ")
print("id rather die than eat that shit")
liveWhere = input("where do you live?: ")
print("what the fuck man")
print()
print("so youre")
print(yourName)
print("you like to eat")
print(goodFood)
print("and you live in")
print(liveWhere)
print()
print("i guess you're pretty cool. rock on. rockauto.")
